repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3.11

-   repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
    -   id: pylint
        args: [--rcfile=.pylintrc]
        additional_dependencies: [pygame==2.5.2, pygame_emojis==0.1.1]
